### ISSUE TITLE
`spec.grafanaContainer.baseImage` unused 

### ISSUE THREAD

**Issue by tamcore** [grafana-operator/grafana-operator-experimental#77]
We've noticed, that the field `spec.grafanaContainer.baseImage` goes unused during reconciliation of the Deployment. 

Although, it is possible to override the image via
```yaml
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: harbor.registry/grafana:1234
```
But that's kinda a lot of overhead, just to overwrite the image. So I hope we can keep the baseImage parameter (as it's already in the current v4 as well) :)

There's also the `initImage` parameter right next to it. But I guess that's obsolete now?

**Comment by NissesSenap** [comment]
Hi @tamcore , first of all thanks allot for trying out version 5 of the operator.

To be honest I had forgotten that we still had the grafanaContainer field in the spec and my guess is that it's a copy from v4. As you point out `initImage` isn't used any more.

My initial thought was that we should remove grafanaContainer, since everything is "supposed" to be done through the deployment value. But as you say at the same time we want to be as user friendly as possible, but as always the question is where do we draw the line.
If we start to add a bunch of value to GrafanaContainer the whole thing of not forcing us to make changes due to specific needs fails fast.

So my suggestion is that we instead of using `grafanaContainer` we change it to `grafanaImage` or `grafanaBaseImage` both works for me and we write a good comment on-top of the struct to show the users what it does.

Then the question is how do we handle if someone defines both?

```
spec:
  grafanaImage: harbor.registry/grafana:1234
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: harbor.registry/grafana:1234
``` 

Should we make the deployment to take precedence or the other way around? Or should we just through an error and say we won't deploy your grafana instance since you define both of them?
In some ways I think an error and a good status message to the end user might be better.

Which way do you feel is best?
