### ISSUE TITLE
Deploying a dashboard with a custom folder doesn't work

### ISSUE THREAD

**Issue by HubertStefanski** [grafana-operator/grafana-operator-experimental#84]
Deploying a folder with the field:
```yaml
spec:
   folder: my-folder
```

Creates the folder on the grafana API of the matching grafana instance, however, the dashboard is never assigned to the folder, resulting in an empty 

Example of bug:

```yaml
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  client:
    preferIngress: true
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: grafanadashboard-from-url-with-folder
spec:
  folder: "my-custom-folder"
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  url: "https://raw.githubusercontent.com/integr8ly/grafana-operator/master/deploy/examples/remote/grafana-dashboard.json"
```
